from pathlib import Path

from docxtpl import DocxTemplate
from spire.doc import Document, FileFormat
from docx import Document as Doc

from config import (
    OUTPUT_PATH,
    TEMPORARY_PATH,
    QUESTIONS_PATH,
    ANSWERS_PATH,
    COVER_PAGE,
    COVER_TEMPLATE,
    COVER_TEMPLATE_ANSWERS,
    TEMPLATE_TITLE_STRING,
    TEMPLATE_ABBREVIATION_STRING,
)
from models import EmployeeData, SubjectData


def create_output_document_path(
    subject: SubjectData, employee: EmployeeData, is_answers_document: bool = False
) -> Path:
    """Create a file path for a test document."""
    subject_abbrev = subject["abbreviation"]
    employee_name = employee["name"]
    employee_license = employee["license"]

    folder_path = OUTPUT_PATH / f"{employee_name} {employee_license}"
    folder_path.mkdir(parents=True, exist_ok=True)

    file_name = f"{employee_name} {employee_license} {subject_abbrev.upper()}"

    if is_answers_document:
        file_name += " odgovori"

    file_name += ".docx"

    return folder_path / file_name


def create_cover_page(subject: SubjectData, is_answers_document: bool = False) -> Path:
    """Create cover page and return temporary file path."""
    if is_answers_document:
        cover_page = DocxTemplate(COVER_TEMPLATE_ANSWERS)
    else:
        cover_page = DocxTemplate(COVER_PAGE)

    context = {
        TEMPLATE_TITLE_STRING: subject["title"],
        TEMPLATE_ABBREVIATION_STRING: subject["abbreviation"],
    }
    cover_page.render(context)

    temp_file = TEMPORARY_PATH / f"cover-{subject['abbreviation']}.docx"
    temp_file.parent.mkdir(parents=True, exist_ok=True)
    cover_page.save(str(temp_file))

    return temp_file


def generate_document_for_subject(
    subject: SubjectData, employee: EmployeeData, is_answers_document: bool = False
) -> Path:
    """Merge cover page with selected question or answer files."""
    subject_abbrev = subject["abbreviation"]

    # Get output document file path
    if is_answers_document:
        output_file_path = create_output_document_path(subject, employee, True)
    else:
        output_file_path = create_output_document_path(subject, employee)

    # Create cover page
    if is_answers_document:
        cover_page_path = create_cover_page(subject, True)
    else:
        cover_page_path = create_cover_page(subject)

    # Create file names from generated numbers
    question_numbers = subject["generated_numbers"]

    # File names for answers
    if is_answers_document:
        files = [
            f"{ANSWERS_PATH}/{subject_abbrev}/{number}.docx"
            for number in question_numbers
        ]
    # File names for questions
    else:
        files = [
            f"{QUESTIONS_PATH}/{subject_abbrev}/{number}.docx"
            for number in question_numbers
        ]

    # Create subject document (containing either questions or answers)
    subject_document = Document()
    subject_document.LoadFromFile(str(cover_page_path))

    # Merge individual documents (questions or answers)
    for i, file in enumerate(files):
        # Append a question or an answer document
        subject_document.InsertTextFromFile(str(file), FileFormat.Auto)

    # Save file compatible with Word 2016
    subject_document.SaveToFile(str(output_file_path), FileFormat.Docx2016)
    subject_document.Close()

    # Delete watermark from the top of the document generated by Spire.Doc
    subject_document = Doc(str(output_file_path))
    subject_document.paragraphs[0].clear()
    subject_document.save(output_file_path)

    return output_file_path


def generate_documents_for_all_subjects(
    subjects: list[SubjectData],
    employee: EmployeeData,
    is_answers_document: bool = False,
) -> list[Path]:
    """Generate tests or test answers for all subjects and return list of output file paths."""
    output_paths: list[Path] = []

    for subject in subjects:
        if is_answers_document:
            output_path = generate_document_for_subject(subject, employee, True)
        else:
            output_path = generate_document_for_subject(subject, employee)

        output_paths.append(output_path)

    return output_paths
